baseURL = 'https://executivetours.gd/'
languageCode = 'en-us'
title = 'Executive Tours'
subtitle = 'Come and Explore Grenada with Executive Tours'
cta = '#'

theme = 'tours'
enableRobotsTXT = true
paginate = 12

[menu]

    [[menu.main]]
    identifier = 'home'
    name = 'Home'
    URL = '/'
    weight = 1

    [[menu.main]]
    identifier = 'services'
    name = 'Services'
    URL = '/services/'
    weight = 2

    [[menu.main]]
    identifier = 'gallery'
    name = 'Gallery'
    URL = '/gallery/'
    weight = 3

    [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    URL = '/contact/'
    weight = 4

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[build]
  writeStats = true