baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Executive Tours'
subtitle = 'Come and Explore Grenada with Executive Tours'
cta = '#'


theme = 'tours'

logo = ''


[menu]

    [[menu.main]]
    identifier = 'home'
    name = 'Home'
    URL = '/'
    weight = 1

    [[menu.main]]
    identifier = 'services'
    name = 'Services'
    URL = '/services/'
    weight = 2

    [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    URL = '/contact/'
    weight = 3

    [[menu.footer]]
    identifier = 'contact'
    name = 'Contact Us'
    URL = '/contact/'
    weight = 1

    [[menu.footer]]
    identifier = 'faq'
    name = 'FAQ'
    URL = '/faq/'
    weight = 2