backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/images
public_folder: /images
collections:
  - name: 'services'
    label: 'Services'
    folder: 'content/services'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    filter: {field: "visible", value: true}
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {label: "Layout", name: "layout", widget: "hidden", default: "services"}
      - { label: 'Image', name: 'image', widget: 'image', required: true }
      - { label: 'Tour Highlights', name: 'services', widget: 'list', fields: [ {label: "Item", name: "item", widget: "string"}] }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - {label: "Visible", name: "visible", widget: hidden, default: true}

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/_index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - { label: 'Hero Section',
              name: 'heroSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: true },
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Enable Button', name: 'button', widget: 'boolean' },
                  { label: 'Button Title', name: 'buttontitle', widget: 'string', required: false },
                  { label: 'Button Url', name: 'buttonurl', widget: 'string' }
                ]
            }
          - { label: 'About Section',
              name: 'aboutSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false },
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                  { label: 'Body', name: 'body', widget: 'markdown' },
                  { label: 'Image', name: 'image', widget: 'image' }
                ]
            }
          - { label: 'Hero Section Two',
              name: 'heroSectionSwo',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Body', name: 'body', widget: 'markdown', required: false },
                  { label: 'Enable Button', name: 'button', widget: 'boolean' },
                  { label: 'Button Title', name: 'buttontitle', widget: 'string', required: false },
                  { label: 'Button Url', name: 'buttonurl', widget: 'string', required: false }
                ]
            }
          - { label: 'Service Section',
              name: 'serviceSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false},
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                  { label: 'Enable Button', name: 'button', widget: 'boolean' },
                  { label: 'Button Title', name: 'buttontitle', widget: 'string', required: false },
                  { label: 'Button Url', name: 'buttonurl', widget: 'string', required: false }
                ]
            }
          - { label: 'Testimonial Section',
              name: 'testimonialSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false},
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                ]
            }

