backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: assets/images
public_folder: /images
collections:
  - name: 'services'
    label: 'Services'
    folder: 'content/services'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    filter: {field: "visible", value: true}
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {label: "Layout", name: "layout", widget: "hidden", default: "services"}
      - { label: 'Image', name: 'image', widget: 'image', required: true }
      - { label: 'Tour Highlights', name: 'services', widget: 'list', fields: [ {label: "Item", name: "item", widget: "string"}] }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - {label: "Visible", name: "visible", widget: hidden, default: true}
  - name: 'testimonial'
    label: 'Testimonial'
    folder: 'content/testimonial'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    filter: {field: "visible", value: true}
    fields:
      - { label: 'Client Name', name: 'clientName', widget: 'string', required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: 'Quote', name: 'quote', widget: "string", required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Client title', name: 'clientTitle', widget: 'string', required: false }
      - {label: "Visible", name: "visible", widget: hidden, default: true}
  - name: 'gallery'
    label: 'Gallery'
    folder: 'content/gallery'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    filter: {field: "visible", value: true}
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - {label: "Visible", name: "visible", widget: hidden, default: true}
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/_index.md'
        label: 'Home Page'
        name: 'home'
        editor:
          preview: false
        fields:
          - { label: 'Hero Section',
              name: 'heroSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: true },
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Enable Button', name: 'enableButton', widget: 'boolean' },
                ]
            }
          - { label: 'About Section',
              name: 'aboutSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false },
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                  { label: 'Body', name: 'body', widget: 'markdown' },
                  { label: 'Image', name: 'image', widget: 'image' }
                ]
            }
          - { label: 'Hero Section Two',
              name: 'heroSectionSwo',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Body', name: 'body', widget: 'markdown', required: false },
                  { label: 'Enable Button', name: 'button', widget: 'boolean' },
                  { label: 'Button Title', name: 'buttontitle', widget: 'string', required: false },
                  { label: 'Button Url', name: 'buttonurl', widget: 'string', required: false }
                ]
            }
          - { label: 'Service Section',
              name: 'serviceSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false},
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                  { label: 'Enable Button', name: 'button', widget: 'boolean' },
                  { label: 'Button Title', name: 'buttontitle', widget: 'string', required: false },
                  { label: 'Button Url', name: 'buttonurl', widget: 'string', required: false }
                ]
            }
          - { label: 'Testimonial Section',
              name: 'testimonialSection',
              widget: "object",
              fields:
                [
                  { label: 'Enable Section', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: false},
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                ]
            }
      - file: 'content/services/_index.md'
        label: 'Services Page'
        name: 'services'
        editor:
          preview: false
        fields:
          - { label: 'Title', name: 'title', widget: "string", required: true }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - file: 'content/contact/_index.md'
        label: 'Contact Page'
        name: 'contact'
        editor:
          preview: false
        fields:
          - { label: 'Title', name: 'title', widget: "string", required: true }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
          - { label: 'Address', name: 'address', widget: 'string', required: false }
          - { label: 'Email', name: 'email', widget: 'string', required: false }
          - { label: 'Phone', name: 'phone', widget: 'string', required: false }
          - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
          - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }
          - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
      - file: 'data/settings.yml'
        label: 'Settings Page'
        name: 'settings'
        editor:
          preview: false
        fields:
          - {
              label: 'Call To Action',
              name: 'callToAction',
              widget: 'object',
              fields:
                [
                  { label: 'Enable', name: 'enable', widget: 'boolean' },
                  { label: 'Title', name: 'title', widget: 'string', required: true },
                  { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Enable Button', name: 'button', widget: 'boolean' },
                  { label: 'Button Title', name: 'buttontitle', widget: 'string', required: false },
                  { label: 'Button Url', name: 'buttonurl', widget: 'string' },
                  {
                    label: 'Enable / Disable on Pages',
                    name: 'enableOrDisable',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Home Page', name: 'homeEnable', widget: 'boolean' },
                        { label: 'Service Page', name: 'serviceEnable', widget: 'boolean' },
                        { label: 'Gallery Page', name: 'galleryEnable', widget: 'boolean' },
                        { label: 'Contact Page', name: 'contactEnable', widget: 'boolean' },
                      ]
                  }
                ]
            }